### ISSUE TITLE
Create a Shooter

### ISSUE THREAD

**Issue by jwong101** [Impact2585/FRCTraining2017#9]
Hopefully we are able to build the shooter in time for TRI. Make sure you have the autonomous working before you start this task, since we may not even have a shooter in the first place. You should use a toggler that toggles the shooter system on and off, so that we don't have to keep holding the button to shoot. There are two motors for the ShooterSystem: one for the agitator and one for the shooter itself. The agitator works by spinning a motor to feed balls into the shooter. The shooter motor is basically a flywheel.

**Comment by rknightly** [comment]
Do I send both of these motors the same signal then? Or is there a difference in terms of when the different motors should be running?

**Comment by jwong101** [comment]
Make them both spin the same direction for now. However, set the shooter motor at max speed and set the agitator motor at half speed.
